version: '2'
services:
  neo4j:
    image: neo4j:latest
    network_mode: host
    restart: always
    environment:
      - NEO4J_AUTH=neo4j/password
    cap_add:
      - SYS_RESOURCE
    ports:
      - "17474:7474"
      - "17687:7687"
      - "11337:1337"
    volumes:
      - /Users/basavarajk/stackroute/code/neo4j_oxygen_java/neo4j/plugins:/plugins
      - /Users/basavarajk/stackroute/code/neo4j_oxygen_java/neo4j/data:/data
      - /Users/basavarajk/stackroute/code/neo4j_oxygen_java/neo4j/plugins:/import
